apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: workload-template
  annotations:
    description: "Description"
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: ${WORKLOAD_NAME}
    name: ${WORKLOAD_NAME}
    namespace: target
  spec:
    containers:
    - image: ${IMAGE}
      imagePullPolicy: Always
      name: ${WORKLOAD_NAME}
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        requests:
          cpu: 100m
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
parameters:
- description: Workload name
  name: WORKLOAD_NAME
- description: Image name
  name: IMAGE
  value: quay.io/dlederer/project1989-dummy-workload:latest
